### ISSUE TITLE
Can't login

### ISSUE THREAD

**Issue by pmsobrado** [pablouser1/plugin.video.filmin#10]
Hi, today I tried your plugin and I'm getting this error:

![imagen](https://github.com/pablouser1/plugin.video.filmin/assets/17699739/09e8835e-7e04-4570-836d-12b0b88f6951)

I'm in Spain and addon is configured with "es" region, using Kodi 20.1 in a Fire TV device. I installed the plugin from the repo.

Thanks in advance.

**Comment by pmsobrado** [comment]
Yep, I had to change it internally hehe. I guess the plugin will auto update itself, right?

Thanks!

**Comment by pablouser1** [comment]
> Y digo yo, porque no hablamos en español? jajaja

Pos también es cierto xdd, cierro la issue entonces

**Comment by pmsobrado** [comment]
El plugin se actualiza solo o tengo que volverlo a meter manualmente?

**Comment by pablouser1** [comment]
Si lo instalaste usando el repositorio debería ser automático
