### ISSUE TITLE
Could Not Connect to Repository

### ISSUE THREAD

**Issue by ridelgad** [pablouser1/plugin.video.filmin#3]
Hola! He instalado el repositorio desde el zip, pero al intentar entrar al repositorio para buscar el addon me sale Could Not Connect To Repository. Alguna idea?

**Comment by pablouser1** [comment]
Hola, quizás intentaste acceder mientras que el servidor estaba cerrado, inténtalo otra vez. También asegúrate de usar la [última versión de mi repositorio](https://kodi.pabloferreiro.es/repository.pabloferreiro/repository.pabloferreiro-1.1.0.zip)
