### ISSUE TITLE
Kodi 18 (CoreELEC 9.2.4)

### ISSUE THREAD

**Issue by opedromandrade** [pablouser1/plugin.video.filmin#4]
Hola. 
Es possible haverlo compatible con Kodi 18 (CoreELEC 9.2.4), o sea una version inferior de python?
Gracias

**Comment by pablouser1** [comment]
Es ténicamente posible, pero no es algo que planeo hacer. Kodi 19 ya está generalmente disponible en distros específicas como LibreELEC y OSMC o de uso general como Debian.

Te recomendaría instalar alguna de estas distros para poner usar este plugin.
